version: "3.4"

services:
  server:
    build: .
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail https://localhost/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - WEB_APP__DOMAIN=localhost
      - ASPNETCORE_ENVIRONMENT=Production
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
    volumes:
      - ./.temp-keys:/root/.aspnet/DataProtection-Keys
      - ./.aspnet/https:/https/:ro
