name: Build and Deploy

on:
  push:
    branches: [ "master" ]

env:
  NETCORE_VERSION: '8.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Tailwind CSS 🎨
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
          chmod +x /usr/local/bin/tailwindcss
          cd ${{ env.WEBAPP_PATH }}
          tailwindcss --input ./src/Client/wwwroot/app.css --output ./src/Client/wwwroot/app.min.css --minify

      - name: Change base href in App.razor to match gh repo name 🏷️
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $NF}')
          sed -i 's/<base href="\/" \/>/<base href="\/'$REPO_NAME'\/" \/>/g' ./src/Client/wwwroot/index.html

      - name: Restore packages 📦
        run: dotnet restore

      - name: Build 🏗️
        run: dotnet build --configuration Release --no-restore

      - name: Test 🧪
        run: dotnet test --no-restore --no-build --verbosity normal

      - name: Publish 📦
        run: dotnet publish ./src/Presentation --configuration Release --no-build --no-restore --output dist

      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          base_branch: master
          branch: gh-pages
          folder: dist/wwwroot
          single_commit: true